### ISSUE TITLE
Fleet Movement Front and Back End

### ISSUE THREAD

**Issue by Sakthisa** [cs361fall2018/project-cartershanesachingrayland#96]
Allowing a particular player to move their fleet twice in a certain direction (N, E, W, S). Need some sort of button or indicator that the player will move their ship. AI should move their ship randomly in a random direction. Backend should handle overlapping logic and prevent ships from "falling" off the edge of the board. This moves will also count as a move, so the opponent will be able to attack, move or place a sonar if they are available. 

Time:
**5 hours**

User Story:
**User Story 3**

**Comment by lunng** [comment]
Front and back end functional, close with merge of fleet
